name: "Terraform"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - "main"

jobs:
  shared:
    uses: DevOpsPlusTeam/github-shared-actions/.github/workflows/terraform/feature-branch.yaml@main