name: "Terraform"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - "main"

jobs:
  shared:
    uses: DevOpsPlusTeam/github-shared-actions/.github/workflows/terraform-pipeline.yaml@main


